/**
 * PWA service worker registration boot file.
 * Registers the service worker generated by vite-plugin-pwa (or a custom sw.js)
 * when running in production. Falls back gracefully if no SW is available.
 */
export default async function ({ app }) {
  if ('serviceWorker' in navigator && import.meta.env.PROD) {
    try {
      await navigator.serviceWorker.register('/sw.js', { scope: '/' })
    } catch (err) {
      // SW registration is best-effort; do not block app startup
      console.warn('[pwa] service worker registration failed:', err)
    }
  }
}
